apiVersion: 1
contactPoints:
  - orgId: 1
    name: Telegram
    receivers:
      - uid: telegram
        type: telegram
        settings:
          bottoken: ${GF_ALERTING_NOTIFICATION_TELEGRAM_BOT_TOKEN}
          chatid: ${GF_ALERTING_NOTIFICATION_TELEGRAM_CHAT_ID}
